version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      CLIENT_URL: ${CLIENT_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - db
      - redis
    command: npm run dev

volumes:
  pgdata:
  redis-data:
