version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - db
    command: npm run dev

volumes:
  pgdata: